<?php 
	$order = $this->order; 
?>


<div style="background-color: #26BEF0; padding: 30px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
  <p style= "color: #FFF;font-size: 12px;">Hello <?php echo $order->name ?>, </p>
  <p style= "color: #FFF;font-size: 12px;">This is <strong>123dj.com</strong> trying to contact you regarding your current order with us. </p>
  <p style= "color: #FFF;font-size: 12px;">Order Status:</p>
  <table width="454" border="1" cellspacing="0">
    <tr>
      <td style="color: #FFF;background-color: #0A6989;font-weight: bold;padding: 5px;" width="126">Order Number</td>
      <td style="color: #FFF;background-color: #0A6989;font-weight: bold;padding: 5px;" width="260">Order Status</td>
    </tr>
    <tr>
      <td style="color: #FFF;padding:5px;background: white;color: #0A6989;font-size: 12px;"><?php echo $order->number ?></td>
      <td style="color: #C10000;padding:5px;background: white;font-size: 12px; font-weight:bold">Shipping and billing address does not match. Order on hold. *</td>
    </tr>
  </table>
  <p style="font-size: 12px; display: block; width: 600px; color: white; ">* When we were trying to process your order, we ran your credit card and
    the receipt printed back to us as a no match address.  This means that address 
    is not the address listed on the credit card. Our policy states that we only
    ship to the billing address of the credit card. Because of credit card fraud
    we are unable to ship your order until we verify that the billing address is
    the same as the shipping address. If this is a problem you can always
    contact your credit card company and add the address you want to ship to as
    an alternate address in the notes and comments section of the credit card
    info. If you feel that this is a mistake please call us and provide the
    1-800 number on the back of the credit card for customer service and we can
    get this pushed through. Sometimes our credit card machine does not read
    debt cards correctly. If this is the address and it is a debt card you can
    email me back your order number and bank phone number so we can just call
    them and verify.
  Thank you for placing your order with us.</p>
  <div style="	background: white;padding: 30px; width: 540px;">
  	<h4 style="	color: #BF0000;	font-size: 18px;background-color: #FFF;padding: 5px;">Please Note:</h4>
  	<p>
  <strong>No emails will be answered regarding this issue. </strong></p>
  	<p>
    PLEASE CALL Toll Free: 1-800-856-8397 and ask for processing department in order to resolve this issue. 
    </p>
  </div>
  <p style="color: #FFF;font-size: 12px;">Thank You,</p>
  <p style="color: #FFF;font-size: 12px;">123dj.com<br />
  </p>
</div>
