<?
	$this->order = $order; 
	
?>

<div class="email-actions-tab-wrapper"> 
	<div class="email-actions-box">
          <div class="email-actions-header">Email Actions:</div>
              <div class="email-actions-wrapper">
                  <button class="email-action-button"  flag="nm"><span>Email No Match</span></button>
                  <button class="email-action-button"  flag="dc"><span>Email Decline</span></button>
                  <button class="email-action-button"  flag="pd"><span>Email Processed</span></button>
                  <button class="email-action-button"  flag="c"><span>Email Confirmation</span></button>
                  <button class="email-action-button"  flag="ns"><span>Email No Stock</span></button>
                  <button class="email-action-button"  flag="ca"><span>Email Canceled</span></button>
              </div>
          </div>
    </div>
</div>
